# Generated by Django 3.2.8 on 2022-06-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Administrator',
        ),
    ]
