# Generated by Django 3.2.8 on 2022-06-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_administrators_administrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
