# Generated by Django 3.2.8 on 2022-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
