# Generated by Django 3.2.8 on 2022-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
