# Generated by Django 3.2.8 on 2022-07-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220705_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_Id',
            new_name='destination_country_id',
        ),
    ]
