# Generated by Django 4.0.4 on 2022-07-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_destination_country_id_flight_destination_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company_id',
            new_name='airline_company',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
    ]
