# Generated by Django 4.0.4 on 2022-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company',
            new_name='airline_company_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country',
            new_name='destination_country_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country',
            new_name='origin_country_id',
        ),
    ]
