# Generated by Django 4.0.4 on 2022-08-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_airline_company_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_company',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company_id',
            new_name='airline_company',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
