# Generated by Django 4.0.4 on 2022-08-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_country_id_airline_company_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
