# Generated by Django 4.0.4 on 2022-08-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_country_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
    ]
